名称：zdm_爬虫

在输入：
  #将下面两行代码取消注释
#将下面两行代码取消注释
  日程安排:
    - cron: "0/15 * * * *"
  工作流触发:

工作:
  构建:
    runs-on:     运行于：ubuntu-latest
    步骤:
    - 使用：     - 使用：actions/checkout@v3
    - 名称:     - 名称: 设置 JDK
      uses:       用途：actions/setup-java@v3
      与:
        java-version: '11'
        分布：'temurin'
        缓存:         缓存：maven
    - 名称:     - 名称: 使用Maven构建
      运行： |
        mvn 包装
        cp ./target/zdm-0.0.1.jar ./zdm.jar
    - 名称:     - 名称: 主要逻辑
      环境:
        #爬取数据时的最大翻页数量#爬取数据时的最大翻页数量
        最大页面大小： 20
        # 点值的数量>minVoted，才会被推送，填0为都推送
        最低投票数: 10
        # 评论的数量>最小评论数，才会被推送，填0为都推送
        最小评论数：2
        # 优惠信息数量>MIN_PUSH_SIZE就会发邮件,否则积累到下一次触发任务再决定是否推送. 不建议填太小的数字,避免邮件太多了
        MIN_PUSH_SIZE: 20
        # 邮箱的smtp服务器地址(示例给出的是qq邮箱的配置,非qq邮箱需要进行修改)# 邮箱的smtp服务器地址(示例给出的是qq邮箱的配置,非qq邮箱需要进行修改)
        emailHost:         emailHost: smtp.qq.com
        # 邮箱smtp服务端口# 邮箱smtp服务端口
        emailPort: 465
        # 接收优惠信息的邮箱 为空代表不进行邮箱推送# 接收优惠信息的邮箱 为空代表不进行邮箱推送
        emailAccount:         emailAccount: ${{secrets.emailAccount}}{{secrets.emailAccount}}
        # 接收优惠信息的邮箱的授权码 为空代表不进行邮箱推送# 接收优惠信息的邮箱的授权码 为空代表不进行邮箱推送
        emailPassword:         emailPassword: ${{secrets.emailPassword}}{{secrets.emailPassword}}
        # WxPusher极简推送模式的spt 为空代表不进行Wx推送# WxPusher极简推送模式的spt 为空代表不进行Wx推送
        spt:         spt: ${{secrets.spt}}{{secrets.spt}}
        # true:下载阶段打印出详细信息(待推送的优惠信息列表,过滤时使用的黑白词),因文本量比较大,在调通项目后可以改为false# true:下载阶段打印出详细信息(待推送的优惠信息列表,过滤时使用的黑白词),因文本量比较大,在调通项目后可以改为false
        detail: false
      run:       运行：java -jar zdm.jar
    #保存已推送和暂未推送的优惠信息#保存已推送和暂未推送的优惠信息
    - name:     - 名称: git添加文件
      run: |
        git add database.db
    - name:     - 名称: 提交 & 推送
      uses:       用途：actions-go/push@master
      with:
        author-email: 'actions@github.com'
        author-name: 'GitHub Actions'
        commit-message: 'update articles'
        token:         令牌: ${{secrets.GIT_TOKEN}}{{secrets.GIT_TOKEN}}
